Repository Skill-Forge-Project/skill_forge, pull requests merged in 2024-03, with the labels that each got.

#9 Navbar buttons fixed
  static/css/navbar.css
  templates/main.html
Labels: frontend

#10 Populating with data from database
  templates/table_template.html
Labels: database, frontend

#11 Successful/unsuccessful unit tests
  app.py
  templates/admin_panel.html
  templates/curr_task_template.html
  templates/main.html
  templates/table_template.html
  templates/user_profile.html
Labels: database, backend, frontend

#12 Edit quest feature implementation
  app.py
  static/css/admin_panel.css
  static/css/admin_panel_table_edit_quest.css
  static/css/edit_quest.css
  static/css/navbar.css
  templates/admin_panel.html
  templates/edit_quest.html
Labels: database, backend, frontend

#15 Successful/unsuccessful unit tests merge into dev_sprint03
  .gitignore
  app.py
Labels: enhancement, backend, frontend

#16 Test cases js merge into dev_sprint03
  .config
  .gitignore
  app.py
  docker-compose.yaml
  js-backend-server/.dockerignore
  js-backend-server/Dockerfile
  js-backend-server/server/curl_test
  js-backend-server/server/findApartment.js
  js-backend-server/server/package-lock.json
  js-backend-server/server/package.json
  js-backend-server/server/server.js
  js-backend-server/server/test.js
  js-backend-server/test.py
  manage.py
  packages_requirements
  templates/curr_task_template.html
  test_runners/run_csharp.py
  test_runners/run_java.py
  test_runners/run_javascript.py
  test_runners/run_python.py
Labels: enhancement, database, backend, frontend

#17 User submit quest form
  .gitignore
  app.py
  static/css/user_submit_quest.css
  templates/admin_panel.html
  templates/main.html
  templates/user_submit_quest.html
  user_submit_quest.py
Labels: enhancement, database, backend, frontend

#31 User profile edit styling
  app.py
  static/css/user_profile.css
  templates/user_profile.html
Labels: enhancement, database, backend, frontend

#35 Tests management
  app.py
  static/css/user_profile.css
  templates/user_profile.html
Labels: enhancement, database, backend, frontend

#32 Navbar template
  admin_submit_quest.py
  app.py
  edit_quest_form.py
  static/css/admin_panel_review_submit_quest.css
  static/css/edit_quest.css
  static/css/edit_submited_quest.css
  static/css/user_profile.css
  static/js/codeMirrorHandling.js
  static/js/questsTable.js
  static/js/showContentsSections.js
  static/js/toggleVisibilitySections.js
  static/scripts.js
  templates/admin_panel.html
  templates/curr_task_template.html
  templates/edit_quest.html
  templates/edit_submited_quest.html
  templates/main.html
  templates/navbar.html
  templates/table_template.html
  templates/user_profile.html
  templates/user_submit_quest.html
  user_submit_quest.py
Labels: enhancement, frontend

#37 Version 1.2-prerelease deployment
  admin_submit_quest.py
  app.py
  edit_quest_form.py
  static/css/admin_panel_review_submit_quest.css
  static/css/edit_quest.css
  static/css/edit_submited_quest.css
  static/css/user_profile.css
  static/js/codeMirrorHandling.js
  static/js/questsTable.js
  static/js/showContentsSections.js
  static/js/toggleVisibilitySections.js
  static/scripts.js
  templates/admin_panel.html
  templates/curr_task_template.html
  templates/edit_quest.html
  templates/edit_submited_quest.html
  templates/main.html
  templates/navbar.html
  templates/table_template.html
  templates/user_profile.html
  templates/user_submit_quest.html
  user_submit_quest.py
Labels: enhancement, database, backend, frontend

#41 Development branch sync with main
  docker-compose.yaml
Labels: enhancement

#44 User Profile page and quests table URLs fix
  admin_submit_quest.py
  app.py
  static/css/admin_panel.css
  static/css/admin_panel_add_quest.css
  static/css/curr_task_template.css
  static/css/edit_quest.css
  static/css/edit_submited_quest.css
  static/css/footer.css
  static/css/login_form.css
  static/css/main_page.css
  static/css/user_profile.css
  static/css/user_submit_quest.css
  static/js/questsTable.js
  templates/admin_panel.html
  templates/footer.html
  templates/main.html
  templates/table_template.html
  templates/user_profile.html
  templates/user_profile_view.html
Labels: enhancement, database, backend, frontend
