Repository Skill-Forge-Project/skill_forge, pull requests merged in 2024-10, with the labels that each got.

#247 Usernames ranklist fix
  app/templates/ranklist_board/ranklist_board.html
Labels: frontend, pull-request

#248 Quest Table updated
  app/templates/quest_table.html
Labels: frontend, pull-request

#249 Enhancement/admin panel track logs
  app/routes/user_routes.py
  app/static/css/edit_quest.css
  app/static/js/codeMirrorHandlingTask.js
  app/static/js/codeMirrorLogsHandling.js
  app/static/js/questsTable.js
  app/templates/admin_panel.html
  app/templates/display_submission_log.html
  requirements.txt
Labels: database, frontend, pull-request

#250 Skill Forge v1.4.1 patch
  Dockerfile
  app/routes/user_routes.py
  app/static/css/edit_quest.css
  app/static/js/codeMirrorHandlingTask.js
  app/static/js/codeMirrorLogsHandling.js
  app/static/js/questsTable.js
  app/templates/admin_panel.html
  app/templates/display_submission_log.html
  app/templates/quest_table.html
  app/templates/ranklist_board/ranklist_board.html
  requirements.txt
  setup.cfg
Labels: deployment, docker-build, pull-request

#257 Input values removed from html on submit quest form
  app/routes/quests_routes.py
  app/templates/open_quest.html
Labels: frontend, pull-request

#258 `Update user profile` form fixed
  app/templates/user_profile.html
Labels: pull-request

#259 Report quest bug-fix & enhancement
  app/static/js/reportQuest.js
  app/templates/open_quest.html
Labels: frontend, pull-request

#260 Skill Forge v1.4.2 patch
  Dockerfile
  app/routes/quests_routes.py
  app/static/js/reportQuest.js
  app/templates/open_quest.html
  app/templates/user_profile.html
  setup.cfg
Labels: deployment, docker-build, pull-request

#264 User profile view - bio field word wrap updated
  app/static/css/user_profile.css
Labels: pull-request

#265 email & username case insensitive during signup
  app/routes/routes.py
  app/templates/register.html
Labels: database, frontend, pull-request

#270 Add length validator (max=500) for 'About me' section
  app/forms.py
Labels: backend, pull-request

#271 Bugfix/update user unique email
  app/routes/user_routes.py
  old-build/Dockerfile.postgres
  old-build/Dockerfile.skill_forge
  old-build/achievements.sql
  old-build/docker-compose.yaml
  old-build/init.sql
  old-build/mongo-init.js
  old-build/setup-postgres.sh
Labels: backend, pull-request

#272 Bugfix/update user profile
  app/forms.py
Labels: pull-request

#273 Skill Forge v1.4.3 patch release
  Dockerfile
  app/forms.py
  app/routes/routes.py
  app/routes/user_routes.py
  app/static/css/user_profile.css
  app/templates/register.html
  app/templates/user_profile_view.html
  old-build/Dockerfile.postgres
  old-build/Dockerfile.skill_forge
  old-build/achievements.sql
  old-build/docker-compose.yaml
  old-build/init.sql
  old-build/mongo-init.js
  old-build/setup-postgres.sh
  setup.cfg
Labels: deployment, docker-build, pull-request

#276 Skill Forge v1.4.4 patch release
  Dockerfile
  setup.cfg
Labels: deployment, docker-build, pull-request

#277 274 enhancement uiux optimizations for bio in my profile
  app/routes/user_routes.py
  app/static/css/user_profile.css
  app/templates/user_profile.html
  app/templates/user_profile_view.html
Labels: frontend, pull-request

#282 Bugfix/user submit quest form
  app/routes/quests_routes.py
  app/routes/user_submit_quest_routes.py
Labels: backend, pull-request

#284 View submited solution form rework
  app/routes/user_submited_solutions.py
Labels: backend, pull-request

#285 Bugfix/contact from rework
  app/forms.py
  app/routes/routes.py
  app/static/css/contact.css
  app/static/css/register.css
  app/templates/register.html
Labels: pull-request

#287 Fix code scanning alert no. 106: Code injection
  app/routes/user_routes.py
  app/routes/user_submit_quest_routes.py
Labels: bug, security

#286 Skill Forge v1.4.5 patch release
  Dockerfile
  app/forms.py
  app/routes/quests_routes.py
  app/routes/routes.py
  app/routes/user_routes.py
  app/routes/user_submit_quest_routes.py
  app/routes/user_submited_solutions.py
  app/static/css/contact.css
  app/static/css/register.css
  app/static/css/user_profile.css
  app/templates/register.html
  app/templates/user_profile.html
  app/templates/user_profile_view.html
  setup.cfg
Labels: deployment, docker-build, pull-request

#289 288 bug user get internal server error when trying to open quest for edit
  app/routes/user_submit_quest_routes.py
Labels: backend, pull-request, bug-fix

#291 submited quests & quest solution tables reorder
  app/routes/user_routes.py
  app/static/js/questsTable.js
  app/templates/user_profile.html
Labels: frontend, pull-request

#292 Skill Forge v1.4.6 patch release
  Dockerfile
  app/models.py
  app/routes/user_routes.py
  app/routes/user_submit_quest_routes.py
  app/static/css/curr_task_template.css
  app/static/js/questsTable.js
  app/templates/navbar.html
  app/templates/open_quest.html
  app/templates/user_profile.html
  app/templates/user_profile_view.html
  setup.cfg
Labels: deployment, docker-build, pull-request

#294 293 bug typo in create account verification
  app/forms.py
Labels: frontend, pull-request, bug-fix

#296 user default avatar set
  app/models.py
Labels: database, backend, pull-request

#297 Skill Forge v1.4.7 patch release
  Dockerfile
  app/forms.py
  app/models.py
  setup.cfg
Labels: database, backend, frontend, pull-request

#301 Icon on quest page fixed
  app/templates/open_quest.html
Labels: frontend, pull-request

#302 Ranklist button reworked
  app/static/css/buttons.css
  app/templates/homepage.html
Labels: frontend, pull-request
