Repository Skill-Forge-Project/skill_forge, pull requests merged in 2024-08, with the labels that each got.

#204 Sync issue-199 with frontend rework
  app/__init__.py
  app/forms.py
  app/models.py
  app/routes/__init__.py
  app/routes/guild_routes.py
  app/routes/quests_routes.py
  app/static/css/guilds/create_guild.css
  app/static/css/guilds/guilds_list.css
  app/static/css/homepage.css
  app/static/css/table.css
  app/static/images/default-guild-avatar.png
  app/static/images/guild_avatar.png
  app/static/js/questsTable.js
  app/templates/guild_templates/create_guild.html
  app/templates/guild_templates/guilds_list.html
  app/templates/homepage.html
Labels: pull-request

#207 Sync UI rework with development
  app/__init__.py
  app/forms.py
  app/models.py
  app/routes/__init__.py
  app/routes/guild_routes.py
  app/routes/quests_routes.py
  app/routes/user_routes.py
  app/static/css/buttons.css
  app/static/css/footer.css
  app/static/css/guilds/create_guild.css
  app/static/css/guilds/guilds_list.css
  app/static/css/homepage.css
  app/static/css/navbar.css
  app/static/css/table.css
  app/static/css/task_page.css
  app/static/css/user_profile.css
  app/static/css/user_profile_BAK.css
  app/static/images/default-guild-avatar.png
  app/static/images/email.jpg
  app/static/images/github.png
  app/static/images/guild_avatar.png
  app/static/js/questsTable.js
  app/templates/footer.html
  app/templates/guild_templates/create_guild.html
  app/templates/guild_templates/guilds_list.html
  app/templates/homepage.html
  app/templates/navbar.html
  app/templates/quest_table.html
  app/templates/user_profile.html
  app/templates/user_profile_BAK.html
  app/templates/user_profile_view.html
  app/templates/user_profile_view_BAK.html
  app/templates/user_submit_quest.html
Labels: frontend, pull-request

#208 Frontend major improvements
  app/static/css/contact.css
  app/static/css/homepage.css
  app/static/css/user_submit_quest.css
  app/templates/contact.html
  app/templates/edit_submited_quest.html
  app/templates/edit_submited_quest_as_user.html
  app/templates/index.html
  app/templates/user_submit_quest.html
  app/templates/view_solution.html
Labels: frontend, pull-request

#209 Sync Development with branch 206
  app/openai/model_setup.py
  app/openai/python_quest.py
  app/static/css/contact.css
  app/static/css/homepage.css
  app/static/css/user_submit_quest.css
  app/templates/contact.html
  app/templates/edit_submited_quest.html
  app/templates/edit_submited_quest_as_user.html
  app/templates/index.html
  app/templates/user_submit_quest.html
  app/templates/view_solution.html
  requirements.txt
Labels: pull-request

#211 Guild info functionaloity
  app/routes/guild_routes.py
  app/static/css/guilds/guild_info.css
  app/templates/guild_templates/guild_info.html
  app/templates/guild_templates/guilds_list.html
Labels: database, backend, frontend, pull-request
