Repository Skill-Forge-Project/skill_forge, pull requests merged in 2024-04, with the labels that each got.

#49 Testing functionality
  .gitignore
  app.py
  templates/curr_task_template.html
  templates/main.html
  templates/navbar.html
  templates/python_tasks.html
  templates/table_template-BACKUP.html
  test_runners/run_csharp.py
  test_runners/run_java.py
  test_runners/run_javascript.py
  test_runners/run_python.py
Labels: enhancement, backend, frontend

#50 Version 1.2.1 deployement
  .gitignore
  admin_submit_quest.py
  app.py
  static/css/admin_panel.css
  static/css/admin_panel_add_quest.css
  static/css/curr_task_template.css
  static/css/edit_quest.css
  static/css/edit_submited_quest.css
  static/css/footer.css
  static/css/login_form.css
  static/css/main_page.css
  static/css/task_page.css
  static/css/user_profile.css
  static/css/user_submit_quest.css
  static/js/questsTable.js
  templates/admin_panel.html
  templates/curr_task_template.html
  templates/footer.html
  templates/main.html
  templates/navbar.html
  templates/python_tasks.html
  templates/table_template-BACKUP.html
  templates/table_template.html
  templates/user_profile.html
  templates/user_profile_view.html
  test_runners/run_csharp.py
  test_runners/run_java.py
  test_runners/run_javascript.py
  test_runners/run_python.py
Labels: deployment, docker-build

#52 multi data type testing fixed
  test_runners/run_javascript.py
  test_runners/run_python.py
Labels: bug, backend

#58 User profile link fix
  .gitignore
  templates/curr_task_template.html
Labels: enhancement, frontend

#60 Codemirror Lib properly implemented on submit solution pages
  static/js/codeMirrorHandlingTask.js
  static/js/updateTestInfo.js
  templates/curr_task_template.html
  templates/edit_quest.html
Labels: bug, invalid, backend, frontend

#61 v1.2.3 Deployment
  .gitignore
  static/js/codeMirrorHandlingTask.js
  static/js/updateTestInfo.js
  templates/curr_task_template.html
  templates/edit_quest.html
Labels: deployment, docker-build

#72 Zero test functionality
  app.py
  static/css/curr_task_template.css
  static/js/updateTestInfo.js
  templates/curr_task_template.html
  test_runners/run_csharp.py
  test_runners/run_java.py
  test_runners/run_javascript.py
  test_runners/run_python.py
Labels: enhancement, backend, frontend

#68 Markdown support
  app.py
  package-lock.json
  package.json
  packages_requirements
  static/css/curr_task_template.css
  static/js/markdownSupport.js
  static/js/updateTestInfo.js
  templates/admin_panel.html
  templates/curr_task_template.html
  templates/edit_quest.html
  templates/user_submit_quest.html
  test_runners/run_csharp.py
  test_runners/run_java.py
  test_runners/run_javascript.py
  test_runners/run_python.py
Labels: enhancement, frontend

#73 v1.2.4 Deployment
  Dockerfile
  app.py
  package-lock.json
  package.json
  packages_requirements
  static/css/curr_task_template.css
  static/css/user_profile.css
  static/js/markdownSupport.js
  static/js/updateTestInfo.js
  templates/admin_panel.html
  templates/curr_task_template.html
  templates/edit_quest.html
  templates/footer.html
  templates/user_profile.html
  templates/user_profile_view.html
  templates/user_submit_quest.html
  test_runners/run_csharp.py
  test_runners/run_java.py
  test_runners/run_javascript.py
  test_runners/run_python.py
Labels: deployment, docker-build

#74 User solutions
  .gitignore
  app.py
  levels.json
  templates/curr_task_template.html
  update_levels_test.py
  user_solutions.py
Labels: enhancement, database, backend, frontend

#48 [Work in progress] Report quest system
  admin_submit_quest.py
  app.py
  edit_quest_form.py
  insert_new_quest.py
  make_json.py
  static/js/questsTable.js
  templates/admin_panel.html
  templates/curr_task_template.html
  templates/edit_reported_quest.html
Labels: database, backend, frontend

#79 Solved quests tables userprofile
  app.py
  static/css/table.css
  static/css/user_profile.css
  static/images/checked.png
  static/images/unchecked.png
  templates/user_profile.html
  templates/view_solution.html
  user_solutions.py
Labels: enhancement, database, frontend

#80 Version 1.2.5 Deploy
  .gitignore
  admin_submit_quest.py
  app.py
  edit_quest_form.py
  insert_new_quest.py
  levels.json
  make_json.py
  requirements.txt
  static/css/table.css
  static/css/user_profile.css
  static/images/checked.png
  static/images/unchecked.png
  static/js/questsTable.js
  templates/admin_panel.html
  templates/curr_task_template.html
  templates/edit_reported_quest.html
  templates/user_profile.html
  templates/user_submit_quest.html
  templates/view_solution.html
  user_solutions.py
Labels: deployment, docker-build

#84 Report quest system functionality
  app.py
  edit_quest_form.py
  static/css/admin_panel_table_edit_quest.css
  static/css/curr_task_template.css
  static/css/edit_quest.css
  templates/admin_panel.html
  templates/curr_task_template.html
  templates/edit_reported_quest.html
Labels: database, backend, frontend

#85 Version 1.2.7 Deployment
  app.py
  edit_quest_form.py
  static/css/admin_panel_table_edit_quest.css
  static/css/curr_task_template.css
  static/css/edit_quest.css
  templates/admin_panel.html
  templates/curr_task_template.html
  templates/edit_reported_quest.html
Labels: deployment, docker-build

#90 Footer rework
  edit_quest_form.py
  static/css/footer.css
  templates/user_profile.html
  templates/user_profile_view.html
Labels: enhancement, frontend

#89 admin_assigned field fixed
  edit_quest_form.py
Labels: database, backend

#92 Social links implementation
  app.py
  static/css/user_profile.css
  static/images/discord.svg
  static/images/facebook.svg
  static/images/github.png
  static/images/github.svg
  static/images/instagram.png
  static/images/linkedin.png
  templates/user_profile.html
  templates/user_profile_view.html
Labels: enhancement, database, backend, frontend

#94 Contributing guidelines
  CONTRIBUTING.md
Labels: documentation

#97 Main Page description and coding descriptions
  app.py
  main_page_info
  main_page_title
  static/css/main_page.css
  static/css/task_page.css
  static/js/markdownSupport.js
  templates/main.html
  templates/python_tasks.html
  templates/table_template.html
Labels: documentation, frontend

#98 Version 1.2.9 Deployment
  app.py
  main_page_info
  main_page_title
  static/css/main_page.css
  static/css/task_page.css
  static/js/markdownSupport.js
  templates/main.html
  templates/python_tasks.html
  templates/table_template.html
Labels: deployment, docker-build

#103 Version 1.3.0 Deployment
  templates/user_profile.html
  templates/user_profile_view.html
Labels: deployment, docker-build, pull-request

#107 Frontend page for handling the registration form errors
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  Dockerfile
  app.py
  static/css/error_page.css
  static/css/login_form.css
  static/images/complain.png
  templates/error_user_exists.html
  templates/footer.html
Labels: enhancement, frontend, pull-request

#109 Comments form showing empty comments issue resolved
  static/css/edit_submited_quest.css
  templates/edit_submited_quest.html
  user_submit_quest.py
Labels: bug, enhancement, pull-request

#111 Enable user interaction commenting on quests
  admin_submit_quest.py
  app.py
  static/css/curr_task_template.css
  static/js/deleteQuestComment.js
  templates/curr_task_template.html
Labels: backend, frontend, pull-request

#112 Implement email functionality for skill forge users
  .gitignore
  admin_submit_quest.py
  app.py
  email_functionality.py
  login_forms.py
  requirements.txt
  static/css/login_form.css
  templates/c_sharp_tasks.html
  templates/email-reset-password-template.html
  templates/email-welcome-template.html
  templates/forgot_password.html
  templates/index.html
  templates/java_tasks.html
  templates/js_tasks.html
  templates/python_tasks.html
  templates/register.html
  templates/reset_password.html
  templates/user_profile_view.html
Labels: enhancement, database, backend, frontend

#113 Version 1.3.1 Deployment
  .gitignore
  Dockerfile
  admin_submit_quest.py
  app.py
  email_functionality.py
  login_forms.py
  requirements.txt
  static/css/curr_task_template.css
  static/css/edit_submited_quest.css
  static/css/error_page.css
  static/css/login_form.css
  static/images/complain.png
  static/js/deleteQuestComment.js
  templates/c_sharp_tasks.html
  templates/curr_task_template.html
  templates/edit_submited_quest.html
  templates/email-reset-password-template.html
  templates/email-welcome-template.html
  templates/error_user_exists.html
  templates/footer.html
  templates/forgot_password.html
  templates/index.html
  templates/java_tasks.html
  templates/js_tasks.html
  templates/python_tasks.html
  templates/register.html
  templates/reset_password.html
  templates/user_profile_view.html
  user_submit_quest.py
Labels: deployment, docker-build, pull-request
