Repository Skill-Forge-Project/skill_forge, pull requests merged in 2024-07, with the labels that each got.

#148 v1.3.9 Deployment
  app/code_runners/run_javascript.py
  app/routes/quests_routes.py
  app/routes/user_submit_quest_routes.py
  app/static/css/homepage.css
  app/static/js/questWaitTime.js
  app/templates/admin_panel.html
  app/templates/homepage.html
  app/templates/open_quest.html
Labels: enhancement, deployment, docker-build, pull-request, bug-fix

#161 158 bugunhandled exceptions triggered by email addresses with cyrillic letters
  Dockerfile
  app/forms.py
  app/routes/routes.py
  app/static/js/userStatus.js
  app/templates/footer.html
  docker-compose.yaml
  setup.cfg
Labels: backend, pull-request, bug-fix

#162 WSGI deployment with cookies fixed
  Dockerfile
  app/__init__.py
  app/forms.py
  app/templates/index.html
  config.py
  requirements.txt
  wsgi.py
Labels: docker-build, pull-request, bug-fix

#165 Validation for password field in the form
  app/forms.py
Labels: database, backend, bug-fix

#180 web sockets on wsgi updated
  Dockerfile
  app/sockets.py
  app/static/dist/bundle.js
  app/static/js/userStatus.js
Labels: backend, pull-request, bug-fix

#181 User registration date registration bug-fix
  app/forms.py
  app/models.py
  app/routes/routes.py
  app/sockets.py
  app/static/js/userStatus.js
  app/templates/index.html
Labels: database, backend, pull-request, bug-fix

#182 Fix user achievement on user profile view page
  app/routes/user_routes.py
  config.py
Labels: frontend, pull-request, bug-fix

#183 User profile page typos fixed
  app/templates/user_profile.html
Labels: frontend, pull-request, bug-fix

#184 Add new background color to dropdown menus options
  app/static/css/admin_panel_add_quest.css
  app/static/css/edit_quest.css
  app/static/css/edit_submited_quest.css
  app/static/css/user_submit_quest.css
Labels: frontend, pull-request, bug-fix

#185 user avatar preview fixed
  app/templates/user_profile.html
Labels: enhancement, pull-request, bug-fix

#186 Deployment v1.3.11
  Dockerfile
  app/forms.py
  app/models.py
  app/routes/routes.py
  app/routes/user_routes.py
  app/static/css/admin_panel_add_quest.css
  app/static/css/edit_quest.css
  app/static/css/edit_submited_quest.css
  app/static/css/user_submit_quest.css
  app/static/dist/bundle.js
  app/static/js/userStatus.js
  app/templates/index.html
  app/templates/user_profile.html
  config.py
Labels: deployment, docker-build, pull-request, bug-fix

#190 Avatar styling and form improvement
  app/static/css/user_profile.css
  app/templates/user_profile.html
Labels: enhancement, frontend, pull-request

#191 404 page handler updated
  app/routes/quests_routes.py
  app/routes/user_routes.py
  app/routes/user_submited_solutions.py
Labels: backend, pull-request, bug-fix

#192 Version 1.3.12 deployment
  app/routes/quests_routes.py
  app/routes/routes.py
  app/routes/user_routes.py
  app/routes/user_submited_solutions.py
  app/static/css/contact.css
  app/static/css/user_profile.css
  app/templates/email-welcome-template.html
  app/templates/user_profile.html
Labels: deployment, docker-build, pull-request

#194 193 enhancementuser status tracking rework
  app/__init__.py
  app/routes/routes.py
  app/sockets.py
  app/static/js/heartBeatStatus.js
  app/static/js/websocket.js
  app/templates/404.html
  app/templates/about.html
  app/templates/admin_panel.html
  app/templates/contact.html
  app/templates/edit_quest.html
  app/templates/edit_reported_quest.html
  app/templates/edit_submited_quest.html
  app/templates/edit_submited_quest_as_user.html
  app/templates/edit_user.html
  app/templates/homepage.html
  app/templates/open_quest.html
  app/templates/quest_table.html
  app/templates/user_profile.html
  app/templates/user_submit_quest.html
  app/templates/view_solution.html
Labels: enhancement, pull-request, javascript

#195 187 enhancementimprove quest comments logic
  app/forms.py
  app/models.py
  app/routes/quests_routes.py
  app/static/js/websocket.js
  app/templates/open_quest.html
Labels: enhancement, database, backend, frontend, pull-request

#196 Sync Dev with Tailwind migration
  app/__init__.py
  app/forms.py
  app/models.py
  app/routes/quests_routes.py
  app/routes/routes.py
  app/routes/user_routes.py
  app/routes/user_submited_solutions.py
  app/sockets.py
  app/static/css/contact.css
  app/static/css/user_profile.css
  app/static/js/heartBeatStatus.js
  app/static/js/websocket.js
  app/templates/404.html
  app/templates/about.html
  app/templates/admin_panel.html
  app/templates/contact.html
  app/templates/edit_quest.html
  app/templates/edit_reported_quest.html
  app/templates/edit_submited_quest.html
  app/templates/edit_submited_quest_as_user.html
  app/templates/edit_user.html
  app/templates/email-welcome-template.html
  app/templates/homepage.html
  app/templates/open_quest.html
  app/templates/quest_table.html
  app/templates/user_profile.html
  app/templates/user_submit_quest.html
  app/templates/view_solution.html
Labels: enhancement, frontend, pull-request

#198 152 enhancement remember me functionality
  app/__init__.py
  app/forms.py
  app/routes/routes.py
  app/static/css/login_form.css
  app/templates/homepage.html
  app/templates/index.html
  app/templates/user_profile_view.html
  config.py
  new_structure.txt
Labels: enhancement, backend, pull-request

#201 Development
  Dockerfile
  app/__init__.py
  app/forms.py
  app/models.py
  app/routes/quests_routes.py
  app/routes/routes.py
  app/sockets.py
  app/static/css/buttons.css
  app/static/css/footer.css
  app/static/css/homepage.css
  app/static/css/input.css
  app/static/css/login_form.css
  app/static/css/navbar.css
  app/static/css/output.css
  app/static/css/styles.css
  app/static/js/heartBeatStatus.js
  app/static/js/updateServerTime.js
  app/static/js/userStatus.js
  app/static/js/websocket.js
  app/templates/404.html
  app/templates/about.html
  app/templates/admin_panel.html
  app/templates/contact.html
  app/templates/edit_quest.html
  app/templates/edit_reported_quest.html
  app/templates/edit_submited_quest.html
  app/templates/edit_submited_quest_as_user.html
  app/templates/edit_user.html
  app/templates/footer.html
  app/templates/homepage.html
  app/templates/index.html
  app/templates/navbar.html
  app/templates/open_quest.html
  app/templates/quest_table.html
  app/templates/user_profile.html
  app/templates/user_profile_view.html
  app/templates/user_submit_quest.html
  app/templates/view_solution.html
  config.py
  new_structure.txt
  package-lock.json
  package.json
  requirements.txt
  setup.cfg
  tailwind.config.js
  webpack.config.js
Labels: deployment, docker-build, pull-request

#202 Sync Main with Guild user story
  Dockerfile
  app/__init__.py
  app/static/js/userStatus.js
  app/static/js/websocket.js
  app/templates/footer.html
  app/templates/homepage.html
  package-lock.json
  package.json
  requirements.txt
  setup.cfg
  webpack.config.js
Labels: pull-request

#203 Sync main with bootstrap_migr
  Dockerfile
  app/__init__.py
  app/forms.py
  app/routes/routes.py
  app/static/css/login_form.css
  app/static/js/userStatus.js
  app/static/js/websocket.js
  app/templates/footer.html
  app/templates/homepage.html
  app/templates/index.html
  app/templates/user_profile_view.html
  config.py
  new_structure.txt
  package-lock.json
  package.json
  requirements.txt
  setup.cfg
  webpack.config.js
Labels: pull-request
